name = "galaxymale"
compatibility_date = "2026-06-20"
assets = { directory = "./public" }

[[routes]]
pattern = "galaxymale.com/*"
zone_name = "galaxymale.com"

[[routes]]
pattern = "www.galaxymale.com/*"
zone_name = "galaxymale.com"
